# Generated by Django 4.2.3 on 2023-08-17 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
        ('accounts', '0002_customuser_facebook_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='students/avatars'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='level',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='levels.level'),
        ),
    ]
