# Generated by Django 4.2.3 on 2023-07-20 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TariffDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_value', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_percent', models.BooleanField(default=True)),
                ('discount_title', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_value', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_percent', models.BooleanField(default=True)),
                ('discount_title', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='tariffdiscount',
            constraint=models.UniqueConstraint(fields=('discount_value', 'is_percent'), name='unique discounts'),
        ),
    ]
