# Generated by Django 4.2.3 on 2023-07-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdiscount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
