# Generated by Django 4.2.3 on 2023-07-20 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_userdiscount_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDiscount',
            new_name='StudentDiscount',
        ),
    ]
