# Generated by Django 4.2.3 on 2023-07-13 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TariffAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('discount_price', models.PositiveIntegerField(default=0)),
                ('day', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='tariffs/images/')),
                ('desc', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('advantages', models.ManyToManyField(blank=True, to='tariffs.tariffadvantage')),
            ],
        ),
    ]
