# Generated by Django 4.2.3 on 2023-08-26 06:35

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_swe', models.CharField(blank=True, max_length=300)),
                ('title_en', models.CharField(blank=True, max_length=300)),
                ('title_e_swe', models.CharField(blank=True, max_length=300)),
                ('desc_swe', ckeditor.fields.RichTextField(blank=True, max_length=700, verbose_name='Swedish')),
                ('desc_en', ckeditor.fields.RichTextField(blank=True, max_length=700, verbose_name='English')),
                ('desc_e_swe', ckeditor.fields.RichTextField(blank=True, max_length=700, verbose_name='Easy Swedish')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('lessons', models.PositiveSmallIntegerField(default=0)),
                ('ordering_number', models.PositiveSmallIntegerField(default=1, unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('chapter_hour', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('chapter_minute', models.PositiveSmallIntegerField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChapterStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_lessons', models.PositiveSmallIntegerField(default=0)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapters.chapter')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('chapter', 'student')},
            },
        ),
    ]
