# That = Bu
# never = hech qachon
# tidy = toza
# cry = yig'lamoq
# take = olish
# say = demoq
# armchair = kreslo
# put = qo'yish
# cupboard = Javon
# boat = qayiq
# coat = palto
# quiet = tinch
# sentence = jumla
# noun = ism
# adverb = olmosh
# definite article = aniq artikl
# indefinite article = noaniq artikl
# adjective = sifatdosh
# verb = fe'l
# preposition = predlog
# plural noun = ko‘plikdagi ot
# singular noun = birlik ot
# pronoun = olmosh
# phrase = ibora
# regular = muntazam
# irregular = tartibsiz
# past simple = o'tgan oddiy
# past participle = O'tgan sifatdosh
