# Generated by Django 4.2.3 on 2023-08-26 06:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('title_swe', models.CharField(blank=True, max_length=200)),
                ('title_e_swe', models.CharField(blank=True, max_length=200)),
                ('level', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
