# Generated by Django 4.2.3 on 2023-08-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ImageField(blank=True, null=True, upload_to='levels/cars/')),
                ('title', models.CharField(max_length=200)),
                ('level', models.PositiveSmallIntegerField(unique=True)),
            ],
        ),
    ]
