# Generated by Django 4.2.3 on 2023-08-16 06:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_eng', models.TextField(blank=True)),
                ('title_swe', models.TextField(blank=True)),
                ('title_l_swe', models.TextField(blank=True)),
                ('text_eng', ckeditor.fields.RichTextField(blank=True)),
                ('text_swe', ckeditor.fields.RichTextField(blank=True)),
                ('text_l_swe', ckeditor.fields.RichTextField(blank=True)),
                ('video_eng', models.FileField(blank=True, null=True, upload_to='')),
                ('video_swe', models.FileField(blank=True, null=True, upload_to='')),
                ('video_l_swe', models.FileField(blank=True, null=True, upload_to='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
