# Generated by Django 4.2.3 on 2023-08-17 10:31

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chapters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=False)),
                ('lesson_time', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('title_swe', models.CharField(blank=True, max_length=300)),
                ('title_en', models.CharField(blank=True, max_length=300)),
                ('title_easy_swe', models.CharField(blank=True, max_length=300)),
                ('text_swe', ckeditor.fields.RichTextField(blank=True, verbose_name='Swedish')),
                ('text_en', ckeditor.fields.RichTextField(blank=True, verbose_name='English')),
                ('text_easy_swe', ckeditor.fields.RichTextField(blank=True, verbose_name='Easy Swedish')),
                ('video_swe', models.FileField(blank=True, null=True, upload_to='')),
                ('video_en', models.FileField(blank=True, null=True, upload_to='')),
                ('video_easy_swe', models.FileField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chapters.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='LessonWordInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('info', models.TextField(max_length=500)),
                ('lesson', models.ManyToManyField(to='lessons.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='LessonSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('link', models.URLField()),
                ('lesson', models.ManyToManyField(to='lessons.lesson')),
            ],
        ),
    ]
