# Generated by Django 4.2.3 on 2023-08-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='title_eng',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title_l_swe',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title_swe',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
