# Generated by Django 4.2.3 on 2023-08-16 06:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_lesson_title_eng_alter_lesson_title_l_swe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='text_l_swe',
        ),
        migrations.AddField(
            model_name='lesson',
            name='text_easy_swe',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Easy Swedish'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='text_eng',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='English'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='text_swe',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Swedish'),
        ),
    ]
