# Generated by Django 4.2.3 on 2023-08-16 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_remove_lesson_text_l_swe_lesson_text_easy_swe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='title_l_swe',
            new_name='title_easy_swe',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='video_l_swe',
            new_name='video_easy_swe',
        ),
    ]
