# Generated by Django 4.2.3 on 2023-08-17 06:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0001_initial'),
        ('lessons', '0004_rename_title_l_swe_lesson_title_easy_swe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('info', models.TextField(max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='text_eng',
            new_name='text_en',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='title_eng',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='video_eng',
            new_name='video_en',
        ),
        migrations.AddField(
            model_name='lesson',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='chapters.chapter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_time',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
