# Generated by Django 4.2.3 on 2023-07-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='student_discount_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tariff',
            name='student_discount_is_percent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tariff',
            name='student_discount_value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tariff',
            name='tariff_discount_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
