# Generated by Django 4.2.3 on 2023-07-20 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tariffday',
            old_name='user_discount_price',
            new_name='student_discount_price',
        ),
    ]
