# Generated by Django 4.2.3 on 2023-07-29 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0002_tariff_student_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='student_discount_is_percent',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='student_discount_value',
        ),
    ]
