# Generated by Django 4.2.3 on 2023-07-20 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tariffs', '0001_initial'),
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_email', models.EmailField(max_length=254)),
                ('student_bonus_price', models.PositiveIntegerField()),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('purchased_price', models.PositiveIntegerField(default=0)),
                ('is_paid', models.BooleanField(default=False)),
                ('stripe_id', models.CharField(blank=True, max_length=100)),
                ('stripe_url', models.URLField(blank=True)),
                ('tariff_title', models.CharField(max_length=100)),
                ('tariff_price', models.PositiveIntegerField()),
                ('tariff_day', models.PositiveSmallIntegerField()),
                ('tariff_discount_value', models.PositiveIntegerField(default=0)),
                ('tariff_discount_is_percent', models.BooleanField(default=False)),
                ('called_user_code', models.CharField(blank=True, max_length=6)),
                ('called_user_email', models.EmailField(blank=True, max_length=254)),
                ('user_discount_price', models.PositiveIntegerField(default=0)),
                ('called_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('tariff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tariffs.tariffday')),
                ('tariff_discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discounts.tariffdiscount')),
            ],
        ),
    ]
