# Generated by Django 4.2.3 on 2023-08-14 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discounts', '0001_initial'),
        ('tariffs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=10)),
                ('student_email', models.EmailField(editable=False, max_length=254)),
                ('student_bonus_amount', models.FloatField(default=0)),
                ('student_discount_amount', models.FloatField(default=0)),
                ('student_discount_value', models.PositiveIntegerField(default=0)),
                ('student_discount_is_percent', models.BooleanField(default=True)),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('use_bonus_money', models.BooleanField(default=False)),
                ('stripe_id', models.CharField(blank=True, max_length=100)),
                ('payment_link', models.URLField(blank=True, null=True)),
                ('stripe_url', models.URLField(blank=True)),
                ('tariff_title', models.CharField(editable=False, max_length=100)),
                ('tariff_price', models.PositiveIntegerField(editable=False)),
                ('tariff_day', models.PositiveSmallIntegerField(editable=False)),
                ('tariff_discount_title', models.CharField(blank=True, editable=False, max_length=200)),
                ('tariff_discount_amount', models.FloatField(default=0, editable=False)),
                ('tariff_discount_value', models.PositiveIntegerField(default=0, editable=False)),
                ('tariff_discount_is_percent', models.BooleanField(default=True, editable=False)),
                ('called_student_code', models.CharField(blank=True, editable=False, max_length=6)),
                ('called_student_email', models.EmailField(blank=True, editable=False, max_length=254)),
                ('called_student_bonus_added', models.BooleanField(default=False, editable=False)),
                ('called_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('tariff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tariffs.tariff')),
                ('tariff_discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discounts.tariffdiscount')),
            ],
        ),
    ]
