# Generated by Django 4.2.3 on 2023-07-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='student_bonus_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
