# Generated by Django 4.2.3 on 2023-08-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount_due',
        ),
        migrations.AddField(
            model_name='order',
            name='use_bonus_money',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='called_student_bonus_added',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='called_student_code',
            field=models.CharField(blank=True, editable=False, max_length=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='called_student_email',
            field=models.EmailField(blank=True, editable=False, max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='student_email',
            field=models.EmailField(editable=False, max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='tariff_day',
            field=models.PositiveSmallIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='tariff_discount_amount',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='tariff_discount_is_percent',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='tariff_discount_title',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='tariff_discount_value',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='tariff_price',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='tariff_title',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
