# Generated by Django 4.2.3 on 2023-08-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_order_amount_due_order_use_bonus_money_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
