# Generated by Django 4.2.3 on 2023-07-20 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_order_student_bonus_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='called_user',
            new_name='called_student',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='called_user_code',
            new_name='called_student_code',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='called_user_email',
            new_name='called_student_email',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_discount_price',
            new_name='student_discount_price',
        ),
    ]
